export default {
	Obad: 'Obadiah',
	Obadiah: 'Obad',
	Phim: 'Philemon',
	Philemon: 'Phim',
	'2John': '2 John',
	'2 John': '2John',
	'3John': '3 John',
	'3 John': '3John',
	Jude: 'Jude',
	Hag: 'Haggai',
	Haggai: 'Hag',
	Joel: 'Joel',
	Nah: 'Nahum',
	Nahum: 'Nah',
	Hab: 'Habakkuk',
	Habakkuk: 'Hab',
	Zeph: 'Zephaniah',
	Zephaniah: 'Zeph',
	'2Thess': '2 Thessalonians',
	'2 Thessalonians': '2Thess',
	Titus: 'Titus',
	'2Pet': '2 Peter',
	'2 Peter': '2Pet',
	Ruth: 'Ruth',
	Jonah: 'Jonah',
	Mal: 'Malachi',
	Malachi: 'Mal',
	Phil: 'Philippians',
	Philippians: 'Phil',
	Col: 'Colossians',
	Colossians: 'Col',
	'2Tim': '2 Timothy',
	'2 Timothy': '2Tim',
	Lam: 'Lamentations',
	Lamentations: 'Lam',
	'1Thess': '1 Thessalonians',
	'1 Thessalonians': '1Thess',
	Jas: 'James',
	James: 'Jas',
	'1Pet': '1 Peter',
	'1 Peter': '1Pet',
	'1John': '1 John',
	'1 John': '1John',
	Gal: 'Galatians',
	Galatians: 'Gal',
	Eph: 'Ephesians',
	Ephesians: 'Eph',
	'1Tim': '1 Timothy',
	'1 Timothy': '1Tim',
	Mic: 'Micah',
	Micah: 'Mic',
	Song: 'Song of Solomon',
	'Song of Solomon': 'Song',
	Amos: 'Amos',
	Ezra: 'Ezra',
	Esth: 'Esther',
	Esther: 'Esth',
	Eccl: 'Ecclesiastes',
	Ecclesiastes: 'Eccl',
	Dan: 'Daniel',
	Daniel: 'Dan',
	Neh: 'Nehemiah',
	Nehemiah: 'Neh',
	'2Cor': '2 Corinthians',
	'2 Corinthians': '2Cor',
	Heb: 'Hebrews',
	Hebrews: 'Heb',
	Hos: 'Hosea',
	Hosea: 'Hos',
	Zech: 'Zechariah',
	Zechariah: 'Zech',
	Mark: 'Mark',
	Rom: 'Romans',
	Romans: 'Rom',
	'1Cor': '1 Corinthians',
	'1 Corinthians': '1Cor',
	Judg: 'Judges',
	Judges: 'Judg',
	John: 'John',
	'1Kgs': '1 Kings',
	'1 Kings': '1Kgs',
	Rev: 'Revelation',
	Revelation: 'Rev',
	Josh: 'Joshua',
	Joshua: 'Josh',
	'2Sam': '2 Samuel',
	'2 Samuel': '2Sam',
	Luke: 'Luke',
	'2Kgs': '2 Kings',
	'2 Kings': '2Kgs',
	Lev: 'Leviticus',
	Leviticus: 'Lev',
	Matt: 'Matthew',
	Matthew: 'Matt',
	Acts: 'Acts',
	'1Chr': '1 Chronicles',
	'1 Chronicles': '1Chr',
	'1Sam': '1 Samuel',
	'1 Samuel': '1Sam',
	Prov: 'Proverbs',
	Proverbs: 'Prov',
	Deut: 'Deuteronomy',
	Deuteronomy: 'Deut',
	Num: 'Numbers',
	Numbers: 'Num',
	'2Chr': '2 Chronicles',
	'2 Chronicles': '2Chr',
	Exod: 'Exodus',
	Exodus: 'Exod',
	Job: 'Job',
	Ezek: 'Ezekiel',
	Ezekiel: 'Ezek',
	Gen: 'Genesis',
	Genesis: 'Gen',
	Jer: 'Jeremiah',
	Jeremiah: 'Jer',
	Isa: 'Isaiah',
	Isaiah: 'Isa',
	Ps: 'Psalms',
	Psalms: 'Ps'
};
