export default {
	Obad: 'Obadiah',
	Phim: 'Philemon',
	'2John': '2 John',
	'3John': '3 John',
	Jude: 'Jude',
	Hag: 'Haggai',
	Joel: 'Joel',
	Nah: 'Nahum',
	Hab: 'Habakkuk',
	Zeph: 'Zephaniah',
	'2Thess': '2 Thessalonians',
	Titus: 'Titus',
	'2Pet': '2 Peter',
	Ruth: 'Ruth',
	Jonah: 'Jonah',
	Mal: 'Malachi',
	Phil: 'Philippians',
	Col: 'Colossians',
	'2Tim': '2 Timothy',
	Lam: 'Lamentations',
	'1Thess': '1 Thessalonians',
	Jas: 'James',
	'1Pet': '1 Peter',
	'1John': '1 John',
	Gal: 'Galatians',
	Eph: 'Ephesians',
	'1Tim': '1 Timothy',
	Mic: 'Micah',
	Song: 'Song of Solomon',
	Amos: 'Amos',
	Ezra: 'Ezra',
	Esth: 'Esther',
	Eccl: 'Ecclesiastes',
	Dan: 'Daniel',
	Neh: 'Nehemiah',
	'2Cor': '2 Corinthians',
	Heb: 'Hebrews',
	Hos: 'Hosea',
	Zech: 'Zechariah',
	Mark: 'Mark',
	Rom: 'Romans',
	'1Cor': '1 Corinthians',
	Judg: 'Judges',
	John: 'John',
	'1Kgs': '1 Kings',
	Rev: 'Revelation',
	Josh: 'Joshua',
	'2Sam': '2 Samuel',
	Luke: 'Luke',
	'2Kgs': '2 Kings',
	Lev: 'Leviticus',
	Matt: 'Matthew',
	Acts: 'Acts',
	'1Chr': '1 Chronicles',
	'1Sam': '1 Samuel',
	Prov: 'Proverbs',
	Deut: 'Deuteronomy',
	Num: 'Numbers',
	'2Chr': '2 Chronicles',
	Exod: 'Exodus',
	Job: 'Job',
	Ezek: 'Ezekiel',
	Gen: 'Genesis',
	Jer: 'Jeremiah',
	Isa: 'Isaiah',
	Ps: 'Psalms'
};
